redash:
  image: redash/redash
  ports:
    - "5000:5000"
  links:
    - redis
    - postgres
  environment:
    REDASH_STATIC_ASSETS_PATH: ../rd_ui/dist/
    REDASH_LOG_LEVEL: INFO
    REDASH_REDIS_URL: redis://redis:6379/0
    REDASH_DATABASE_URL: postgresql://postgres@postgres/postgres
    REDASH_COOKIE_SECRET: rehash:cookie
    REDASH_ALLOW_SCRIPTS_IN_USER_INPUT: true
redis:
  image: redis
postgres:
  image: postgres
  volumes:
    - "./postgres:/docker-entrypoint-initdb.d"
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  links:
    - redash
